#CICD Pipeline

trigger:
    branches:
        include:
        - main
        - deploy/*

        exclude:
        - hotfix/*
    batch: true

stages:
- stage: Build
  jobs:
  - job: CIJob
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Build Job'
    steps:
    - template: '/Build/build-pipeline.yml'
      parameters:
          buildConfig: 'debug'
    - template: '/Build/build-pipeline.yml'
      parameters:
          buildConfig: 'release'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact Task'
      inputs:
        ArtifactName: 'depo'
        PathtoPublish: '$(build.artifactsstaging)'
        

# - stage: Checks
#   dependsOn: Build
#   pool: server
#   jobs:
#   - job: Validation
#     steps:
#     - task: ManualValidation@1
#       inputs:
#         notifyUsers: |
#           310538-PA7@deccansoftstudents.onmicrosoft.com
#           1728233@kiit.ac.in
#         instructions: '1728233@kiit.ac.in'

- stage: Azure
  #dependsOn: Checks
  dependsOn: Build
  jobs:
  - deployment: VM
    #dependsOn: WebApp
    environment:
      name: Hybrid-Pools
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: IISWebAppManagementOnMachineGroup@0
          #   inputs:
          #     EnableIIS: true
          #     IISDeploymentType: 'IISWebsite'
          #     ActionIISWebsite: 'CreateOrUpdateWebsite'
          #     WebsiteName: 'Default Web Site'
          #     WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
          #     WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
          #     AddBinding: true
          #     ParentWebsiteNameForApplication: 'Default Web Site'
          #     ParentWebsiteNameForVD: 'Default Web Site'
          #     Bindings: '{
          #       "bindings":[
          #         {
          #           "protocol": "http",
          #           "ipAddress": "All Unassigned",
          #           "port": "80",
          #           "hostname": "Default Web Site",
          #           "sslThumbprint": "",
          #           "sniFlag": false
          #         }
          #       ]
          #     }'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/7d169ca8-2755-4870-b45c-bfc651013a77/46639ef8e327f00ab1a941288dd28abe/dotnet-hosting-8.0.7-win.exe" -OutFile $env:temp\DotNetCore.WindowsHosting.exe
                Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
              errorActionPreference: 'silentlyContinue'
              verbosePreference: 'continue'

          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(System.ArtifactsDirectory)/**/release/*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true


  # - job: WebApp
  #   steps:
  #   - task: DownloadBuildArtifacts@1
  #     displayName: 'download artifact for webapp'
  #     inputs:
  #       buildType: 'current'
  #       downloadType: 'single'
  #       artifactName: 'depo'
  #       downloadPath: '$(System.ArtifactsDirectory)/DownloadedFiles'

  #   - task: AzureRmWebAppDeployment@4
  #     inputs:
  #       ConnectionType: 'AzureRM'
  #       azureSubscription: 'Lifeline233-SP'
  #       appType: 'webApp'
  #       WebAppName: 'hybrid-apphjdmbulew44re'
  #       packageForLinux: '$(System.ArtifactsDirectory)/**/release/*.zip'


# - stage: AWS
#   dependsOn: Checks
#   jobs:
#   - job: ArtifactDownload
#     steps:
#     - task: DownloadBuildArtifacts@1
#       displayName: 'Download Build Artifact'
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'depo'
#         itemPattern: 'depo/MyBuilds/debug'
#         downloadPath: '$(system.artifactsstaging)'
    


